// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCCFa8czcN6unDfRh9CAMI-HT48m5c7qg',
    appId: '1:101533588273:web:ce81fc2ddac87ceb91ae10',
    messagingSenderId: '101533588273',
    projectId: 'testerprojecthome',
    authDomain: 'testerprojecthome.firebaseapp.com',
    storageBucket: 'testerprojecthome.appspot.com',
    measurementId: 'G-PLTRM23N0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCifXnj0gx-SJhE6izTiCat02s9olAtQVI',
    appId: '1:101533588273:android:d29e6a021cdd97d191ae10',
    messagingSenderId: '101533588273',
    projectId: 'testerprojecthome',
    storageBucket: 'testerprojecthome.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoWenLGf07DMgNt2U2n5pFsaQEFw5JtI4',
    appId: '1:101533588273:ios:952c028d6f4ef54891ae10',
    messagingSenderId: '101533588273',
    projectId: 'testerprojecthome',
    storageBucket: 'testerprojecthome.appspot.com',
    iosBundleId: 'com.example.homeTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoWenLGf07DMgNt2U2n5pFsaQEFw5JtI4',
    appId: '1:101533588273:ios:952c028d6f4ef54891ae10',
    messagingSenderId: '101533588273',
    projectId: 'testerprojecthome',
    storageBucket: 'testerprojecthome.appspot.com',
    iosBundleId: 'com.example.homeTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCCFa8czcN6unDfRh9CAMI-HT48m5c7qg',
    appId: '1:101533588273:web:89e5a48f113bf71d91ae10',
    messagingSenderId: '101533588273',
    projectId: 'testerprojecthome',
    authDomain: 'testerprojecthome.firebaseapp.com',
    storageBucket: 'testerprojecthome.appspot.com',
    measurementId: 'G-5FNY6M040G',
  );
}
